### ISSUE TITLE
Bringing help

### ISSUE THREAD

**Issue by TrevorSmale** [RepRapLtd/Oxygen-concentrator#2]
Hello I was just looking over the project and noticed that I may be able to help by sending people over. Our project (Open Lung) has seen tremendous growth with many skilled specialists who could probably speed up the dev of the oxygen concentrator.

**Comment by iotleaf** [comment]
Hi Trevor

Is this the code for your project?

https://gitlab.com/open-source-ventilator/ventilator/OpenLung/-/raw/master/control-electronics/Electr.Sys._Concept-Specific/smb-controller-concept-1/arduino/OpenSourceVentilator.ino

-------------------------------
@line 1088 you are comparing rather than assigning values
 breathe==tick-breathLength;
did you mean 
 breathe=tick-breathLength;
-------------------------------
@lines 651 & 652 you are assinging rather than comparing values
     if (ch='V') CVmode=true; 
     if (ch='P') CVmode=false; 
did you mean
     if (ch=='V') CVmode=true; 
     if (ch=='P') CVmode=false; 
-------------------------------
@line 1074 missing semicolon
-------------------------------

Can you let me know if these are errors or intentional please?

Thanks,
Michael

**Comment by RepRapLtd** [comment]
Please have this discussion in the correct place:

https://gitlab.com/groups/open-source-ventilator/ventilator/-/issues
